[package]
name = "playground"
version = "0.1.0"
authors = ["calebwin <calebhwin@gmail.com>"]
edition = "2018"

[dependencies]
# em = "0.1.3"
em   = { path = "../../emu" }
ocl  = "0.19.2"
either = "1.5.2"